apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsboard-enterprise
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: opsboard-enterprise
  template:
    metadata:
      labels:
        app: opsboard-enterprise
    spec:
      containers:
        - name: opsboard-enterprise
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
