apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opsboard-enterprise-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: opsboard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opsboard-enterprise-service
                port:
                  number: 3000
