apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-lite
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudwatch-lite
  template:
    metadata:
      labels:
        app: cloudwatch-lite
    spec:
      containers:
        - name: cloudwatch-lite
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
