apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-lite-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cloudwatch-lite
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
