apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsboard-enterprise-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/fouad211/devops-gitops.git
    targetRevision: main
    path: opsboard-enterprise/helm
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: opsboard-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
