replicaCount: 1

image:
  repository: ghcr.io/fouad211/opsboard-enterprise
  tag: ecf6a3278b608ecd0a423e7370399ff151afa215
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

env:
  PORT: "3000"
